

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/department_management
    username: root
    password: root
  security:
    user:
      name: ayoub
      password: ayoub
  jpa:
    hibernate:
      ddl-auto: update
